### ISSUE TITLE
mark 3.11 version as end of life

### ISSUE THREAD

**Issue by binnes** [okd-project/planning#13]
We need a process to 'archive' older versions of the documentation.  There is a need to keep 3.11 as there are community members with 3.11 estate that is in plan to get upgraded.  We also need to look at older 4.x versions too

**Comment by mburke5678** [comment]
@binnes We should keep the 3.11 docs for OCP and OKD on line after EOL. We will no longer update EOL docs, however

**Comment by elmiko** [comment]
we discussed this issue at the okd community development meeting today. a little more context from the okd perspective is that even though OCP and Red Hat still support 3.11, the okd community is not able to support these older versions and does not plan to backport to them. we would like a way to denote in the docs that this version is not maintained by the okd community, but that the docs remain as a reference.

we are slightly concerned that the presence of the docs give the impression that the okd community supports the version, which we do not. but we acknowledge that there are community members who are still using version 3.11.

**Comment by binnes** [comment]
Centos use End of Build - could we adopt that?

**Comment by mburke5678** [comment]
@binnes Do we know what the full wording the CentOS uses? I cannot find it on the web.

**Comment by binnes** [comment]
@mburke5678 This is all I can find : https://www.centos.org/download/.  The docs don't have anything to indicate if the version is still current/being maintained

**Comment by binnes** [comment]
@mburke5678 This has been implemented, but only the latest version has been left untagged.  The actual version should also be left untagged, so currently 4.12 and latest should be untagged

**Comment by binnes** [comment]
this is implemented and reviewed in meeting 30 May
