### ISSUE TITLE
Collect use cases for feature toggle

### ISSUE THREAD

**Issue by binnes** [okd-project/planning#16]
from the technical meeting.  Introduce OKD feature toggle functionality
- request for use cases

There is also a possible option to allow tech preview with upgrade, normally enabling tech preview disables upgrades

**Comment by binnes** [comment]
notes from 23 Aug meeting:

- would also be good to have the option to uninstall and cleanup a feature

**Comment by elmiko** [comment]
this is also about allowing granular selection of TechPreview features so that the FeatureGate does not enable them all.

**Comment by binnes** [comment]
no interest from community, so closing
