### ISSUE TITLE
Create Documentation for Single Node Installation (non-assisted installer)

### ISSUE THREAD

**Issue by lmzuccarelli** [okd-project/planning#28]
This is installing a SNO OKD cluster the "hard way"  using UPI (user provisioned infrastructure) 

Details for editing website: https://www.okd.io/wg_docs/okd-io/

Current link to google doc https://docs.google.com/document/d/19QjzNBDRgNiTk-LGki_xpi-lv8i_LRgf3dpOHSQ-_YI/edit

Please ping me for access

**Comment by lmzuccarelli** [comment]
@mtulio - yes that would be great. The thinking here was to give the community a way of deploying SNO OKD, albeit the hard way (for educational learning purposes on bare metal/vm's) - home lab usage .

Maybe we could create another ticket specficying how to deploy on AWS using ansible  etc

**Comment by binnes** [comment]
Draft at https://docs.google.com/document/d/19QjzNBDRgNiTk-LGki_xpi-lv8i_LRgf3dpOHSQ-_YI/edit from @luigizuccarelli

**Comment by lmzuccarelli** [comment]
Created this PR https://github.com/okd-project/okd.io/pull/25 - reviews are welcome !!!

**Comment by binnes** [comment]
No issues raised on published content so closing
