### ISSUE TITLE
Review guides section docs

### ISSUE THREAD

**Issue by binnes** [okd-project/planning#3]
Move the home lab content to blogs then create a section or page with links to home labs content

**Comment by binnes** [comment]
notes from 23 Aug meeting
- Internal RedHat team working on install guides, look forward to some contributions from them

**Comment by durandom** [comment]
I created something based on terraform and assisted installer https://github.com/operate-first/ionos-openshift/tree/main/terraform-ocp
Happy to come up with a format for OKD installs

**Comment by binnes** [comment]
Merged into #29.  Decided to move guides to blog entries, as these are dated.
