### ISSUE TITLE
Construct Survey 2023

### ISSUE THREAD

**Issue by JaimeMagiera** [okd-project/planning#33]
Next survey is being constructed here...

https://docs.google.com/forms/d/e/1FAIpQLScw5Qbt-iMorF4LdqzgwGY84eplmfGVq0xmN-LVrNv16g-2aA/viewform?usp=sf_link

**Comment by mburke5678** [comment]
Would it make sense to add a question on _which_ documentation folks use?

https://www.docs.okd.io
https://www.okd.io/docs/ 
Both
Other: ______________

**Comment by JaimeMagiera** [comment]
Added that question, as well as a few others, and have sent out the survey.
