### ISSUE TITLE
Define the process to locally view a doc PR

### ISSUE THREAD

**Issue by binnes** [okd-project/planning#35]
How can a member of the community create a PR, verify it is a valid PR (page builds) - openshift docs

**Comment by binnes** [comment]
explore a route to create a container, so community members can easily build the page to validate before a pull request is created

**Comment by elmiko** [comment]
i've talked to some folks internally and have a solution we could document. i am going to assign this to myself and move to "in progress".

**Comment by elmiko** [comment]
i have used the following process to build and view local changes to the docs project:

1. check out the documentation repo
    ```
    git clone https://github.com/openshift/openshift-docs
    ```
2. build the site using the included dockerfile
    ```
   podman run --rm -it -v `pwd`:/docs:Z quay.io/openshift-cs/asciibinder asciibinder build --distro openshift-origin
   ```
3. inspect output files in `./_preview/openshift-origin/latest/`

i tried this process from a fresh checkout today and things seemed to work well. a couple caveats to note:

1. you will most likely see some error output that looks like this:
    ```
    WARN: The following branches do not exist in your local git repo:
    - enterprise-3.10
    - enterprise-3.11
    - enterprise-3.6
    - enterprise-3.7
    - enterprise-3.9
    - enterprise-4.11
    - enterprise-4.6
    - enterprise-4.7
    The build will proceed but these branches will not be generated.
    WARN: The /docs/_topic_map.yml20230919-1-628e1m file on branch 'OSDOCS-7251-Azure-CPMS-mutli-subnet' references 215 nonexistent topics. Set logging to 'debug' for details.
    WARN: Branch OSDOCS-7251-Azure-CPMS-mutli-subnet includes 6073 files that are not referenced in the /docs/_topic_map.yml20230919-1-bhydnn file. Set logging to 'debug' for details.
    ```
    i have been informed that this is a normal type of warning and doesn't necessarily need investigation.
2. the root index file will be `./index-community.html`, but this file does not link properly to the content in `./_preview` directory. if you want to see the main page for the version, the file is `./_preview/openshift-origin/latest/welcome/index.html`

where do we want to land these instructions?

**Comment by elmiko** [comment]
created https://github.com/okd-project/okd.io/pull/36 to fix this.
