### ISSUE TITLE
create a video where we show how to take a failure and triage/debug back to the test

### ISSUE THREAD

**Issue by binnes** [okd-project/planning#4]
create a video where we show how to take a failure and triage/debug back to the test. to share with the community how we try to chase down these bugs (elmiko, Bruce Link with Diane M)

**Comment by elmiko** [comment]
i'm definitely game for this, i would like to reach out to a colleague on my team to see if we could get a couple developers to do this walk through. i've started to make some local notes on a storyboard for this video.

**Comment by elmiko** [comment]
cc @lobziik would be a great person to join in on this

**Comment by elmiko** [comment]
just to share my thoughts, for a storyboard i'm thinking something like this:

1. start on https://amd64.origin.releases.ci.openshift.org/
2. have a small discussion about what this page is and what users can learn from it, diving into a recent release and explaining the parts of the page
3. find a failed test on a release, click through into the prow console and explain what it is
4. examine the failure to explain how we look for information and where we go to understand failure messages and test sources
5. spend some time talking about flaky tests and methods that someone might use to sort the _wheat from the chaff_
6. even though it's not okd specific, show how to use https://search.ci.openshift.org/ to find similar error messages
7. spend some time talking about how we go from the error logs in the test output to the source code repositories that is being tested
8. talk about opening bugs on ocp versus okd, maybe talk about the relationship a little bit
9. questions and answers

how does this sound to folks as a starter?

**Comment by elmiko** [comment]
i talked with @lobziik about scheduling for this and i think the week of 29 Aug will probably work best. i will attend the working group meeting today to see if i can sync up with @dmueller2001 about timing,

**Comment by elmiko** [comment]
talked about this at the community meeting today, a couple great suggestions came out of the discussion
* when looking at the failures/tests, make sure to mention about upgrading versus installing for issues. eg "this issue will only affect new installs"
* ask around the community for inspiration about troubles they've had with these interfaces, release or prow. would be awesome to have someone like @bdlink on the video as well.

**Comment by elmiko** [comment]
i have setup a meeting this friday at 1200 ET with @lobziik and @dmueller2001

**Comment by elmiko** [comment]
we created the video today, i'm guessing we can move this to done once @dmueller2001 publishes?

**Comment by elmiko** [comment]
@binnes i think we can close this now that the blog has been published.
