### ISSUE TITLE
Define a "Getting Started" page for OKD/OpenShift beginners

### ISSUE THREAD

**Issue by binnes** [okd-project/planning#5]
Define an entry point for beginners

This topic being discussed : https://github.com/openshift/okd/discussions/1286

**Comment by mburke5678** [comment]
Would any of the material  in the OCP Getting Started book be useable in OKD? 

https://docs.openshift.com/container-platform/4.10/getting_started/openshift-overview.html

**Comment by SriRamanujam** [comment]
What level of knowledge should we expect readers to have? Are they presumed to be familiar with Kubernetes, with Docker/containers?

**Comment by mburke5678** [comment]
We could probably use most, if not all, of this OCP doc: [Kubernetes overview](https://docs.openshift.com/container-platform/4.11/getting_started/kubernetes-overview.html)
