### ISSUE TITLE
migrate openshift/okd repo to okd-project org

### ISSUE THREAD

**Issue by binnes** [okd-project/planning#9]
Migrate okd main reposiotry from the OpenShift github org to okd-project org.  There are no dependencies, so this can be moved at any time.

**Comment by binnes** [comment]
@LorbusChris, @vrutkovs do you have authority in the OpenShift org and repo to change ownership to the okd-org?

**Comment by vrutkovs** [comment]
Internal DPP team will do the transfer -  https://issues.redhat.com/browse/DPP-10961

**Comment by elmiko** [comment]
just wanted to leave an update here, the linked issue is not able to be made public (apologies to those without access).

with that said, the request has been approved for the transfer.

**Comment by vrutkovs** [comment]
Done, repo moved to okd-project. openshift/okd would also be redirected there
